# Generated by Django 3.2.8 on 2024-08-09 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_unit_measures'),
        ('inventory', '0014_category_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_measures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.unit_measures'),
        ),
    ]
