# Generated by Django 3.2.8 on 2024-08-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_product_unit_measures'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_reserved',
            name='type_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
