# Generated by Django 3.2.8 on 2024-09-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_subcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percentages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
