# Generated by Django 3.2.8 on 2024-06-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0128_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='UDn8I1cvN6', max_length=10),
        ),
    ]
