# Generated by Django 3.2.8 on 2024-08-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0129_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='G3PBdBRMtx', max_length=10),
        ),
    ]
