# Generated by Django 3.2.8 on 2024-08-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0132_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='neB52smzW1', max_length=10),
        ),
    ]
