# Generated by Django 3.2.8 on 2024-08-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0136_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='reiTc7DPS9', max_length=10),
        ),
    ]
