# Generated by Django 3.2.8 on 2024-08-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0138_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='fZiF5Wjpx9', max_length=10),
        ),
    ]
