# Generated by Django 3.2.8 on 2024-09-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0139_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='mcUorXBCML', max_length=10),
        ),
    ]
