# Generated by Django 3.2.8 on 2024-09-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0143_alter_branch_psswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='logo_branch',
            field=models.ImageField(blank=True, default='Logo_Company/withOut.png', null=True, upload_to='Logo_branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='Pi9rvI8dm6', max_length=30),
        ),
    ]
