# Generated by Django 3.2.8 on 2024-09-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0146_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='5XxMuLFf5e', max_length=30),
        ),
    ]
