# Generated by Django 3.2.8 on 2024-09-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0147_alter_branch_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='psswd',
            field=models.CharField(default='cVs4CFdVzq', max_length=30),
        ),
    ]
