# Generated by Django 3.2.8 on 2024-06-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0124_auto_20240509_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='utmEgq9HbVJI2sNOp1lG', max_length=20, unique=True),
        ),
    ]
