# Generated by Django 3.2.8 on 2024-08-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0128_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='QoaMpnSdk0jDzE7uAqJJ', max_length=20, unique=True),
        ),
    ]
