# Generated by Django 3.2.8 on 2024-08-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0131_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='kIL8vxaQT8nSjDUCevT7', max_length=20, unique=True),
        ),
    ]
