# Generated by Django 3.2.8 on 2024-08-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0133_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='oN3EVjsfoElFZn6BL3Q6', max_length=20, unique=True),
        ),
    ]
