# Generated by Django 3.2.8 on 2024-08-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0134_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='Cim22T720mYWF5kEYLHj', max_length=20, unique=True),
        ),
    ]
