<<<<<<< HEAD
# Generated by Django 3.2.8 on 2024-09-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0137_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='0lMYS10HfL0qnkeomcmE', max_length=20, unique=True),
        ),
    ]
=======
# Generated by Django 3.2.8 on 2024-09-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0137_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='0lMYS10HfL0qnkeomcmE', max_length=20, unique=True),
        ),
    ]
>>>>>>> 9aa4991e267538f22eeecff4bc0d53723478e8b2
