
# Generated by Django 3.2.8 on 2024-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0138_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            # field=models.CharField(default='1YUm0EwcfElI8DXlKf7x', max_length=20, unique=True),
            field=models.CharField(default='8FPENAqPVEoOaLIyib0G', max_length=20, unique=True),
        ),
    ]
