# Generated by Django 3.2.8 on 2024-09-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0140_alter_employee_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='MilCxHV0rPnB9ckAQL2Y', max_length=20, unique=True),
        ),
    ]
