# Generated by Django 3.2.8 on 2024-09-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0143_auto_20240924_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='psswd',
            field=models.CharField(default='vYnh7LFTDzONaiey4NvV', max_length=20, unique=True),
        ),
    ]
