# Generated by Django 3.2.8 on 2024-08-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0026_alter_invoice_consumption_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='QRStr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
