# Generated by Django 3.2.8 on 2024-08-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0027_alter_invoice_qrstr'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='attacheddocument',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
