# Generated by Django 3.2.8 on 2024-08-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_unit_measures'),
        ('invoice', '0028_invoice_attacheddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_invoice',
            name='unit_measures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.unit_measures'),
        ),
    ]
