# Generated by Django 3.2.8 on 2024-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0030_alter_details_invoice_unit_measures'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='QRStr_nc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='attacheddocument_nc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='urlinvoicepdf_nc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='urlinvoicexml_nc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
