# Generated by Django 3.2.8 on 2024-09-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0031_auto_20240918_1749'),
        ('invoice', '0031_auto_20240918_1852'),
    ]

    operations = [
    ]
