# Generated by Django 3.2.8 on 2024-09-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0032_merge_0031_auto_20240918_1749_0031_auto_20240918_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('date_created', models.DateField()),
                ('accounting_code', models.CharField(max_length=30)),
                ('accounting_account', models.CharField(max_length=100)),
                ('identification', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('debit', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
            options={
                'verbose_name': 'Accounting Entry',
                'verbose_name_plural': 'Accounting Entries',
            },
        ),
    ]
